version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: sales-api-node-app
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: sales-api-node-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales-api-node

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis-sales-api-node
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: sales-api-node-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=italocovas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db

